### ISSUE TITLE
Doc search causes server timeout for short strings

### ISSUE THREAD

**Issue by camoy** [SWI-Prolog/plweb#19] opened 2017-05-23 17:27 UTC
Getting `Error 503 first byte timeout` when attempting to search documentation (and not selecting something from the dropdown). For example, navigating to: <http://www.swi-prolog.org/search?for=is&x=0&y=0>

**Comment by wouterbeek** [comment] 2017-06-10 10:01
I can reproduce this for search string `is`.  This seems to result in an overly intensive search task and then cause a server timeout.

The search feature does still work for other/longer strings (adapting this issue's subject to reflect this).

**Comment by JanWielemaker** [comment] 2017-06-10 14:53
Yes.  The search is not the problem.  It takes only 50ms.  After that it starts generating a huge HTML
page with zillion of results.   Ideally, I guess, we'd properly rank the pages and show the top N hits.  Ranking is hard though.   Could we do anything better that tf-idf?  Not sure how many links we have.
Possibly we could meaningfully do page rank?  Of course for `is` the best is probably to only return
the page for `is/2'.

**Comment by JanWielemaker** [comment] 2017-06-10 15:10
Hmm.  A lot seems to be disk I/O.  Running it on my home desktop with ssd it does the job in 7 seconds (producing a 1.1 Mb HTML file).

**Comment by wouterbeek** [comment] 2017-06-10 18:49
@JanWielemaker There are two tasks here: (1) ranking the long list of search results and (2) adding pagination over the result set.  I have used pagination extensively to deal with large result sets, specifically the LDF browser over the LOD-a-lot file: http://webscale.cc:3001/LOD-a-lot

The pagination code has its own page over at https://github.com/wouterbeek/pagination, which supports generating pagination objects (represented as SWI dictionaries), setting the HTTP Link header, and rendering an HTML pager widget (using Bootstrap 4).

**Comment by JanWielemaker** [comment] 2018-12-08 17:03
In the `apropos/1` predicate of library(help) I started a more meaningful search and ranking.  This should be merged.

**Comment by JanWielemaker** [comment] 2018-12-11 21:52
There is still a lot to improve, but this issue can be considered closed IMO.

**Closed by JanWielemaker** 2018-12-11 21:52 UTC
Labels: bug
